################################################
# service/config/database.ymlを以下の内容で上書き #
################################################

# AS-IS
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

# TO-BE
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %> # 変更
  password: <%= ENV['MYSQL_PASSWORD'] %> #変更
  host: <%= ENV['MYSQL_HOST'] %> # 変更